version: "3.0"

services:

  hugo:
    image: jojomi/hugo:latest
    volumes:
      - ./src/:/src
      - ./output/:/output
    ports:
      - 1313

  img-convert:
    image: acleancoder/imagemagick-full
    volumes:
      - ./src/:/src
