baseurl = "http://städ.lyheden.com"
title = "Lyheden Städtjänst"
theme = "dimension"
languageCode = "sv-se"
defaultContentLanguage = "sv"
enableRobotsTXT = true
disableKinds=["RSS"]
publishDir = "/output"

# footer: <div>Icon made from <a href="http://www.onlinewebfonts.com/icon">Icon Fonts</a> is licensed by CC BY 3.0</div>

[params]
  description = '<!--[-->Varmt Välkommen till Lyheden Städ Tjänst AB!<!--]--><br /> 
    <!--[-->En liten och väl inarbetad firma i din närhet.<!--]-->' 
  #logo = "fa-diamond"
  logoimage = "images/2a768ad82432e230a09ceccfe4b01082.svg"
  copyright = "Lyheden Städtjänst AB - Organisationsnummer 556646-2031"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.sv]
languageName = "Svenska"
weight = 1

